import { uid } from "./id";
import {
  emptyWizardRespuestas,
  type AppData,
  type Cliente,
  type Movimiento,
  type Persona,
  type Presupuesto,
  type Servicio,
} from "./types";

function iso(y: number, m: number, d: number): string {
  return `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
}

export function seedData(): AppData {
  const now = new Date();
  const y = now.getFullYear();
  const m = now.getMonth() + 1;
  const prevM = m === 1 ? 12 : m - 1;
  const prevY = m === 1 ? y - 1 : y;

  // ---------- Equipo ----------
  const directora: Persona = {
    id: uid("per"),
    nombre: "Julia Fontán",
    rol: "Directora y fundadora",
    esDirectora: true,
    tipoContratacion: "mensual",
    sueldoFijo: 900000,
    valorHora: 0,
    valorJornada: 0,
    valorPieza: 0,
    porcentajeProyecto: 0,
    clientesAsignados: [],
    observaciones: "Dirección creativa general y cuentas clave.",
    activa: true,
  };
  const disenadora: Persona = {
    id: uid("per"),
    nombre: "Ana Solari",
    rol: "Diseñadora gráfica",
    esDirectora: false,
    tipoContratacion: "mensual",
    sueldoFijo: 480000,
    valorHora: 8000,
    valorJornada: 0,
    valorPieza: 12000,
    porcentajeProyecto: 0,
    clientesAsignados: [],
    observaciones: "",
    activa: true,
  };
  const productora: Persona = {
    id: uid("per"),
    nombre: "Carla Núñez",
    rol: "Productora",
    esDirectora: false,
    tipoContratacion: "jornada",
    sueldoFijo: 0,
    valorHora: 9000,
    valorJornada: 65000,
    valorPieza: 0,
    porcentajeProyecto: 0,
    clientesAsignados: [],
    observaciones: "Coordina producciones fotográficas y de video.",
    activa: true,
  };
  const creadora: Persona = {
    id: uid("per"),
    nombre: "Micaela Ibarra",
    rol: "Creadora de contenido",
    esDirectora: false,
    tipoContratacion: "cliente",
    sueldoFijo: 0,
    valorHora: 7000,
    valorJornada: 55000,
    valorPieza: 9000,
    porcentajeProyecto: 0,
    clientesAsignados: [],
    observaciones: "",
    activa: true,
  };
  const communityManager: Persona = {
    id: uid("per"),
    nombre: "Rocío Paz",
    rol: "Community manager",
    esDirectora: false,
    tipoContratacion: "mensual",
    sueldoFijo: 340000,
    valorHora: 6000,
    valorJornada: 0,
    valorPieza: 0,
    porcentajeProyecto: 0,
    clientesAsignados: [],
    observaciones: "",
    activa: true,
  };
  const equipo = [directora, disenadora, productora, creadora, communityManager];

  // ---------- Clientes ----------
  const clientes: Cliente[] = [
    {
      id: uid("cli"),
      marca: "Bruma Cosmética",
      contacto: "Valentina Ríos",
      telefono: "+54 9 11 4455-0101",
      email: "valen@brumacosmetica.com",
      instagram: "@bruma.cosmetica",
      rubro: "Belleza",
      fechaInicio: iso(y, m > 4 ? m - 4 : 12 + m - 4, 1),
      estado: "activo",
      serviciosContratados: [],
      abonoMensual: 620000,
      moneda: "ARS",
      fechaPago: "5",
      modalidadPago: "Transferencia, primeros 5 días del mes",
      observaciones: "Cliente ancla. Prioriza reels y fotografía de producto.",
      equipoAsignado: [disenadora.id, creadora.id, communityManager.id],
    },
    {
      id: uid("cli"),
      marca: "Terrena Café",
      contacto: "Julián Meza",
      telefono: "+54 9 11 4455-0102",
      email: "julian@terrena.cafe",
      instagram: "@terrena.cafe",
      rubro: "Gastronomía",
      fechaInicio: iso(y, m > 8 ? m - 8 : 12 + m - 8, 15),
      estado: "activo",
      serviciosContratados: [],
      abonoMensual: 480000,
      moneda: "ARS",
      fechaPago: "10",
      modalidadPago: "Transferencia mensual",
      observaciones: "Foco en contenido gastronómico y cobertura de eventos.",
      equipoAsignado: [creadora.id, communityManager.id],
    },
    {
      id: uid("cli"),
      marca: "Casa Lino",
      contacto: "Delfina Aguirre",
      telefono: "+54 9 11 4455-0103",
      email: "delfina@casalino.com.ar",
      instagram: "@casalino.hogar",
      rubro: "Indumentaria y hogar",
      fechaInicio: iso(y, m > 12 ? 1 : 1, 1),
      estado: "activo",
      serviciosContratados: [],
      abonoMensual: 710000,
      moneda: "ARS",
      fechaPago: "1",
      modalidadPago: "Transferencia, adelantado",
      observaciones: "Producción de moda mensual + dirección creativa.",
      equipoAsignado: [directora.id, disenadora.id, productora.id],
    },
    {
      id: uid("cli"),
      marca: "Estudio Cielo Arquitectura",
      contacto: "Nicolás Ferreyra",
      telefono: "+54 9 11 4455-0104",
      email: "nico@estudiocielo.com.ar",
      instagram: "@estudiocielo.arq",
      rubro: "Arquitectura",
      fechaInicio: iso(y, m > 2 ? m - 2 : 12 + m - 2, 20),
      estado: "activo",
      serviciosContratados: [],
      abonoMensual: 390000,
      moneda: "ARS",
      fechaPago: "8",
      modalidadPago: "Transferencia mensual",
      observaciones: "Gestión de redes + fotografía de obra una vez al mes.",
      equipoAsignado: [communityManager.id],
    },
    {
      id: uid("cli"),
      marca: "Flor Salvaje Florería",
      contacto: "Camila Ortiz",
      telefono: "+54 9 11 4455-0105",
      email: "cami@florsalvaje.com.ar",
      instagram: "@florsalvaje",
      rubro: "Retail",
      fechaInicio: iso(y, m > 6 ? m - 6 : 12 + m - 6, 3),
      estado: "activo",
      serviciosContratados: [],
      abonoMensual: 340000,
      moneda: "ARS",
      fechaPago: "12",
      modalidadPago: "Transferencia mensual",
      observaciones: "",
      equipoAsignado: [creadora.id],
    },
    {
      id: uid("cli"),
      marca: "Nudo Joyería",
      contacto: "Sofía Bianchi",
      telefono: "+54 9 11 4455-0106",
      email: "sofia@nudojoyeria.com",
      instagram: "@nudo.joyeria",
      rubro: "Joyería",
      fechaInicio: "",
      estado: "potencial",
      serviciosContratados: [],
      abonoMensual: 0,
      moneda: "ARS",
      fechaPago: "",
      modalidadPago: "",
      observaciones: "Primera reunión hecha, esperando aprobación de presupuesto.",
      equipoAsignado: [],
    },
    {
      id: uid("cli"),
      marca: "Verde Menta Nutrición",
      contacto: "Lucía Weiss",
      telefono: "+54 9 11 4455-0107",
      email: "lucia@verdementa.com.ar",
      instagram: "@verdementa.nutricion",
      rubro: "Salud y bienestar",
      fechaInicio: "",
      estado: "presupuesto_enviado",
      serviciosContratados: [],
      abonoMensual: 0,
      moneda: "ARS",
      fechaPago: "",
      modalidadPago: "",
      observaciones: "",
      equipoAsignado: [],
    },
  ];

  const [bruma, terrena, casaLino] = clientes;

  // ---------- Servicios ----------
  const S = (
    nombre: string,
    categoria: string,
    participacionPct: number,
    unidad: Servicio["unidad"],
    horasEstimadas: number,
    costoInterno: number,
    profesionalResponsable: string,
    margenMinimo: number,
    complejidad: Servicio["complejidad"]
  ): Servicio => ({
    id: uid("srv"),
    nombre,
    categoria,
    participacionPct,
    unidad,
    horasEstimadas,
    costoInterno,
    profesionalResponsable,
    margenMinimo,
    complejidad,
    observaciones: "",
  });

  const servicios: Servicio[] = [
    S("Estrategia de redes sociales", "Estrategia", 20, "proyecto", 8, 90000, "Directora y fundadora", 30, "media"),
    S("Gestión integral de redes sociales", "Gestión", 100, "mes", 30, 210000, "Community manager", 30, "media"),
    S("Community management", "Gestión", 100, "mes", 14, 90000, "Community manager", 30, "baja"),
    S("Planificación mensual de contenido", "Estrategia", 15, "mes", 6, 45000, "Productora", 30, "baja"),
    S("Calendario de contenidos", "Estrategia", 10, "mes", 4, 30000, "Community manager", 30, "baja"),
    S("Copywriting", "Contenido", 10, "pieza", 1, 4000, "Copywriter", 30, "baja"),
    S("Diseño gráfico", "Diseño", 25, "pieza", 1.5, 6000, "Diseñadora gráfica", 35, "media"),
    S("Historias de Instagram", "Contenido", 10, "pieza", 0.5, 2000, "Creadora de contenido", 35, "baja"),
    S("Posts estáticos", "Contenido", 20, "pieza", 1, 4000, "Diseñadora gráfica", 35, "baja"),
    S("Carruseles", "Contenido", 15, "pieza", 2, 7000, "Diseñadora gráfica", 35, "media"),
    S("Reels", "Contenido", 25, "pieza", 3, 13000, "Creadora de contenido", 35, "media"),
    S("Edición de reels", "Edición", 15, "pieza", 1.5, 6000, "Editora de video", 35, "media"),
    S("Filmación de contenido", "Producción", 30, "jornada", 4, 35000, "Videógrafa", 30, "media"),
    S("Fotografía de producto", "Fotografía", 30, "jornada", 4, 30000, "Fotógrafa", 30, "media"),
    S("Fotografía gastronómica", "Fotografía", 30, "jornada", 4, 38000, "Fotógrafa", 30, "media"),
    S("Producción de moda", "Producción", 100, "jornada", 8, 100000, "Productora", 25, "alta"),
    S("Producción gastronómica", "Producción", 100, "jornada", 6, 85000, "Productora", 25, "alta"),
    S("Dirección creativa", "Dirección", 20, "proyecto", 6, 60000, "Directora y fundadora", 35, "alta"),
    S("Dirección de arte", "Dirección", 20, "jornada", 5, 48000, "Directora y fundadora", 35, "alta"),
    S("Estilismo", "Producción", 20, "jornada", 5, 40000, "Estilista", 30, "media"),
    S("Búsqueda de locación", "Producción", 10, "proyecto", 3, 18000, "Asistente de producción", 30, "baja"),
    S("Armado de set", "Producción", 10, "jornada", 3, 22000, "Asistente de producción", 30, "media"),
    S("Cobertura de eventos", "Producción", 100, "jornada", 6, 90000, "Fotógrafa", 25, "alta"),
    S("Campañas", "Dirección", 100, "proyecto", 24, 260000, "Directora y fundadora", 30, "alta"),
    S("Lanzamientos de marca", "Dirección", 100, "proyecto", 32, 380000, "Directora y fundadora", 30, "alta"),
    S("Identidad visual", "Diseño", 100, "proyecto", 20, 190000, "Diseñadora gráfica", 35, "alta"),
    S("Asesoría de imagen", "Consultoría", 100, "hora", 1, 40000, "Estilista", 40, "media"),
    S("Consultoría creativa", "Consultoría", 100, "hora", 1, 45000, "Directora y fundadora", 40, "media"),
  ];

  const svc = (nombre: string) => servicios.find((s) => s.nombre === nombre)!;

  // ---------- Presupuestos ----------
  const itemsDesdeServicios = (pairs: [string, number][]) =>
    pairs.map(([nombre, cantidad]) => {
      const s = svc(nombre);
      return {
        id: uid("item"),
        servicioId: s.id,
        nombre: s.nombre,
        cantidad,
        unidad: s.unidad,
        precioUnitario: s.costoInterno,
        costoUnitario: s.costoInterno,
        participacionPct: s.participacionPct,
      };
    });

  const p1: Presupuesto = {
    id: uid("pre"),
    numero: 1,
    clienteId: casaLino.id,
    nombreCliente: casaLino.marca,
    contacto: casaLino.contacto,
    fecha: iso(prevY, prevM, 2),
    validezDias: 15,
    estado: "aprobado",
    moneda: "ARS",
    tipoCambio: 1000,
    respuestas: { ...emptyWizardRespuestas(), tipoMarca: "Indumentaria y hogar", integrantesEquipo: 3 },
    items: itemsDesdeServicios([
      ["Gestión integral de redes sociales", 1],
      ["Producción de moda", 1],
      ["Dirección creativa", 1],
      ["Reels", 4],
      ["Posts estáticos", 8],
    ]),
    costosAdicionales: [
      { id: uid("cad"), categoria: "Alquiler de locación", descripcion: "Estudio fotográfico", monto: 35000 },
      { id: uid("cad"), categoria: "Modelos", descripcion: "1 modelo, jornada completa", monto: 60000 },
      { id: uid("cad"), categoria: "Traslados", descripcion: "Traslado equipo + modelo", monto: 15000 },
    ],
    impuestosPct: 10,
    comisionesPct: 3,
    margenMinimoPct: 20,
    margenSugeridoPct: 35,
    margenPremiumPct: 50,
    fondoImprevistosPct: 8,
    precioElegido: "sugerido",
    precioManual: 0,
    distribucion: [
      { id: uid("dist"), categoria: "Pago de diseñadora gráfica", personaId: disenadora.id, tipo: "fijo", valor: 90000 },
      { id: uid("dist"), categoria: "Pago de productora", personaId: productora.id, tipo: "fijo", valor: 100000 },
      { id: uid("dist"), categoria: "Costos de producción", personaId: null, tipo: "fijo", valor: 110000 },
      { id: uid("dist"), categoria: "Mi sueldo como directora", personaId: directora.id, tipo: "porcentaje", valor: 15 },
      { id: uid("dist"), categoria: "Ganancia de TRAMA", personaId: null, tipo: "porcentaje", valor: 20 },
      { id: uid("dist"), categoria: "Impuestos", personaId: null, tipo: "porcentaje", valor: 10 },
    ],
    introduccion: "Propuesta de gestión creativa integral para Casa Lino.",
    objetivos: "Fortalecer la identidad visual de la marca y aumentar el engagement mensual.",
    entregables: "8 posts, 4 reels, 1 jornada de producción de moda, dirección creativa del mes.",
    cronograma: "Trabajo mensual, entregas semanales de contenido.",
    formaPago: "50% al inicio del mes, 50% a los 15 días.",
    condiciones: "Los cambios de último momento pueden implicar costo adicional.",
    serviciosNoIncluidos: "Pauta publicitaria, fotografía de producto para e-commerce.",
    observaciones: "",
  };

  const p2: Presupuesto = {
    id: uid("pre"),
    numero: 2,
    clienteId: clientes[6].id,
    nombreCliente: "Verde Menta Nutrición",
    contacto: "Lucía Weiss",
    fecha: iso(y, m, 8),
    validezDias: 15,
    estado: "enviado",
    moneda: "ARS",
    tipoCambio: 1000,
    respuestas: { ...emptyWizardRespuestas(), tipoMarca: "Salud y bienestar", integrantesEquipo: 2 },
    items: itemsDesdeServicios([
      ["Community management", 1],
      ["Reels", 3],
      ["Posts estáticos", 6],
      ["Historias de Instagram", 12],
    ]),
    costosAdicionales: [{ id: uid("cad"), categoria: "Gestión del proyecto", descripcion: "Coordinación mensual", monto: 20000 }],
    impuestosPct: 10,
    comisionesPct: 3,
    margenMinimoPct: 20,
    margenSugeridoPct: 35,
    margenPremiumPct: 50,
    fondoImprevistosPct: 8,
    precioElegido: "sugerido",
    precioManual: 0,
    distribucion: [],
    introduccion: "Propuesta de gestión de redes sociales para Verde Menta Nutrición.",
    objetivos: "Generar una comunidad activa y comunicar los valores de la marca.",
    entregables: "6 posts, 3 reels, 12 historias mensuales.",
    cronograma: "Trabajo mensual, planificación los días 1 de cada mes.",
    formaPago: "Pago mensual adelantado.",
    condiciones: "Validez de la propuesta: 15 días.",
    serviciosNoIncluidos: "Fotografía profesional, pauta publicitaria.",
    observaciones: "",
  };

  const p3: Presupuesto = {
    id: uid("pre"),
    numero: 3,
    clienteId: clientes[5].id,
    nombreCliente: "Nudo Joyería",
    contacto: "Sofía Bianchi",
    fecha: iso(y, m, 15),
    validezDias: 10,
    estado: "borrador",
    moneda: "ARS",
    tipoCambio: 1000,
    respuestas: { ...emptyWizardRespuestas(), tipoMarca: "Joyería", integrantesEquipo: 2 },
    items: itemsDesdeServicios([
      ["Identidad visual", 1],
      ["Fotografía de producto", 1],
      ["Diseño gráfico", 6],
    ]),
    costosAdicionales: [{ id: uid("cad"), categoria: "Utilería", descripcion: "Props para bodegón de producto", monto: 12000 }],
    impuestosPct: 10,
    comisionesPct: 3,
    margenMinimoPct: 20,
    margenSugeridoPct: 35,
    margenPremiumPct: 50,
    fondoImprevistosPct: 8,
    precioElegido: "sugerido",
    precioManual: 0,
    distribucion: [],
    introduccion: "Propuesta de identidad visual y set fotográfico inicial para Nudo Joyería.",
    objetivos: "Construir una identidad visual sólida y un banco de imágenes de producto.",
    entregables: "Manual de marca básico, 1 jornada de fotografía de producto, 6 piezas de diseño.",
    cronograma: "Proyecto puntual, 3 semanas de duración estimada.",
    formaPago: "50% al aprobar, 50% contra entrega.",
    condiciones: "No incluye impresión de materiales físicos.",
    serviciosNoIncluidos: "Gestión de redes sociales, pauta publicitaria.",
    observaciones: "",
  };

  const presupuestos = [p1, p2, p3];

  // ---------- Movimientos (mes actual + mes anterior, para comparar) ----------
  const movimientos: Movimiento[] = [];
  const addMov = (
    mov: Omit<Movimiento, "id" | "moneda" | "tipoCambio" | "comprobante" | "observaciones" | "medioPago"> &
      Partial<Pick<Movimiento, "medioPago">>
  ) => {
    movimientos.push({
      ...mov,
      id: uid("mov"),
      moneda: "ARS",
      tipoCambio: 1000,
      comprobante: "",
      observaciones: "",
      medioPago: mov.medioPago ?? "Transferencia",
    });
  };

  const clientesMensuales = [bruma, terrena, casaLino, clientes[3], clientes[4]];
  for (const mesLoop of [{ mm: prevM, yy: prevY }, { mm: m, yy: y }]) {
    for (const c of clientesMensuales) {
      addMov({
        fecha: iso(mesLoop.yy, mesLoop.mm, Number(c.fechaPago) || 5),
        tipo: "ingreso_cliente",
        categoria: "Abono mensual",
        descripcion: `Abono mensual ${c.marca}`,
        clienteId: c.id,
        proyectoId: null,
        personaId: null,
        monto: c.abonoMensual,
        estado: mesLoop.mm === m ? (c === clientes[4] ? "pendiente" : "cobrado") : "cobrado",
      });
    }
    // Gastos operativos fijos
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 3),
      tipo: "alquiler",
      categoria: "Alquiler",
      descripcion: "Alquiler de estudio/oficina",
      clienteId: null,
      proyectoId: null,
      personaId: null,
      monto: 220000,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 5),
      tipo: "software",
      categoria: "Software",
      descripcion: "Suite de diseño + herramientas de gestión",
      clienteId: null,
      proyectoId: null,
      personaId: null,
      monto: 45000,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 6),
      tipo: "transporte",
      categoria: "Transporte",
      descripcion: "Traslados a producciones",
      clienteId: null,
      proyectoId: null,
      personaId: null,
      monto: 38000,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 7),
      tipo: "gasto_produccion",
      categoria: "Producción",
      descripcion: "Materiales para producción fotográfica",
      clienteId: bruma.id,
      proyectoId: null,
      personaId: null,
      monto: 52000,
      estado: "pagado",
    });
    // Sueldos
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 1),
      tipo: "pago_sueldo",
      categoria: "Sueldos",
      descripcion: "Sueldo Julia Fontán — Directora",
      clienteId: null,
      proyectoId: null,
      personaId: directora.id,
      monto: directora.sueldoFijo,
      estado: mesLoop.mm === m ? "pendiente" : "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 1),
      tipo: "pago_sueldo",
      categoria: "Sueldos",
      descripcion: "Sueldo Ana Solari — Diseñadora gráfica",
      clienteId: null,
      proyectoId: null,
      personaId: disenadora.id,
      monto: disenadora.sueldoFijo,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 1),
      tipo: "pago_sueldo",
      categoria: "Sueldos",
      descripcion: "Sueldo Rocío Paz — Community manager",
      clienteId: null,
      proyectoId: null,
      personaId: communityManager.id,
      monto: communityManager.sueldoFijo,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 20),
      tipo: "pago_freelance",
      categoria: "Freelance",
      descripcion: "Jornada de producción — Carla Núñez",
      clienteId: casaLino.id,
      proyectoId: null,
      personaId: productora.id,
      monto: productora.valorJornada,
      estado: "pagado",
    });
    addMov({
      fecha: iso(mesLoop.yy, mesLoop.mm, 18),
      tipo: "pago_freelance",
      categoria: "Freelance",
      descripcion: "Reels del mes — Micaela Ibarra",
      clienteId: bruma.id,
      proyectoId: null,
      personaId: creadora.id,
      monto: 4 * creadora.valorPieza,
      estado: "pagado",
    });
  }

  return {
    clientes,
    servicios,
    equipo,
    presupuestos,
    movimientos,
    config: {
      nombreEstudio: "TRAMA Studio",
      nombreDirectora: "Julia Fontán",
      monedaPrincipal: "ARS",
      tipoCambioDefault: 1000,
      porcentajeImpuestos: 10,
      comisionesPct: 3,
      margenGananciaMinimo: 20,
      margenGananciaSugerido: 35,
      margenGananciaPremium: 50,
      fondoImprevistos: 8,
      porcentajeReinversion: 15,
      sueldoObjetivoDirectora: 900000,
      modalidadSueldoDirectora: "fijo_mas_porcentaje",
      sueldoFijoDirectora: 900000,
      porcentajeSueldoDirectora: 15,
      categoriasGastos: [
        "Producción",
        "Sueldos",
        "Freelance",
        "Suscripciones",
        "Alquiler",
        "Transporte",
        "Publicidad",
        "Equipamiento",
        "Software",
        "Impuestos",
        "Viáticos",
        "Otros",
      ],
      datosBancarios: "CBU 0000003100000000000000 — Banco ejemplo — TRAMA Studio SRL",
      datosFiscales: "TRAMA Studio SRL — CUIT 30-00000000-0",
    },
  };
}
